name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore ./Poker_PreflopRange/Poker_PreflopRange.csproj

      - name: Build
        run: dotnet build ./Poker_PreflopRange/Poker_PreflopRange.csproj --no-restore

      - name: Publish
        run: dotnet publish ./Poker_PreflopRange/Poker_PreflopRange.csproj -c Release -o release --nologo

      # Change the base-tag in index.html from '/' to 'Poker_PreflopRange' to match GitHub Pages repository subdirectory
      - name: Change base-tag in index.html
        run: sed -i 's/<base href="\/" \/>/<base href="\/Poker_PreflopRange\/" \/>/g' release/wwwroot/index.html

      # The 404.html file is already in the wwwroot directory and handles SPA routing
      # Update the base href in 404.html as well
      - name: Change base-tag in 404.html
        run: |
          if [ -f release/wwwroot/404.html ]; then
            echo "404.html already exists with SPA routing support"
          else
            cp release/wwwroot/index.html release/wwwroot/404.html
          fi

      # Add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: release/wwwroot
